### ISSUE TITLE
Lab 1-3

### ISSUE THREAD

**Issue by AlekseiMaslakov** [iamnzrv/JavaChallenges#1]
Здравствуйте

Lab1:
- a) Исключений накидали, а обрабатывать их кто будет?)
- b) См. а)
- c) Не хочется такое, например, в finally вынести? Дублирование кода ведь.
![image](https://user-images.githubusercontent.com/14160551/65874016-653e8200-e38d-11e9-9d17-19d55a036bfe.png)
Изначально файла с данными нет, при запуске создаётся файл, в который будет записан пустой лист иии...всё? Дальше только после добавления книг руками?)
Lab2: Что с инкапсуляцией? Публичные поля и тут же геттеры для них? Разберитесь с модификаторами доступа в коде. Ну и всё свалено в один пакет непонятно почему. 
Lab3: Ok, кроме того же, что и в Lab2 - не смотрите на модификаторы

**Comment by iamnzrv** [comment]
Спасибо, добавил коммит

**Comment by iamnzrv** [comment]
> Здравствуйте
> 
> Lab1:
> 
> * a) Исключений накидали, а обрабатывать их кто будет?)
> * b) См. а)
> * c) Не хочется такое, например, в finally вынести? Дублирование кода ведь.
>   ![image](https://user-images.githubusercontent.com/14160551/65874016-653e8200-e38d-11e9-9d17-19d55a036bfe.png)
>   Изначально файла с данными нет, при запуске создаётся файл, в который будет записан пустой лист иии...всё? Дальше только после добавления книг руками?)
>   Lab2: Что с инкапсуляцией? Публичные поля и тут же геттеры для них? Разберитесь с модификаторами доступа в коде. Ну и всё свалено в один пакет непонятно почему.
>   Lab3: Ok, кроме того же, что и в Lab2 - не смотрите на модификаторы

Спасибо, исправил в новом коммите

**Comment by yonzoo** [comment]
@AlekseiMaslakov, понял, принял и исправил ошибки в новых коммитах)

**Comment by AlekseiMaslakov** [comment]
Lab2 - а что изменилось-то?) Замена паблика на протектед в данном случае ничего ведь не меняет
Lab3 - использование лямбд это хорошо, но куда аннотацию потеряли тогда?

**Comment by yonzoo** [comment]
@AlekseiMaslakov, Исправлено
